version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: corrente_amiga
      MYSQL_USER: root
      MYSQL_PASSWORD: 159753Br@
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql

  api:
    build: .
    ports:
      - 3333:3333
    depends_on:
      - mysql
